package com.mycompany.quanlytruyen.view.post;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mycompany.quanlytruyen.config.AppConfig;
import com.mycompany.quanlytruyen.dao.AccountDAO;
import com.mycompany.quanlytruyen.dao.BookDao;
import com.mycompany.quanlytruyen.dao.ChapterDao;
import com.mycompany.quanlytruyen.dao.DataSourceFactory;
import com.mycompany.quanlytruyen.model.Account;
import com.mycompany.quanlytruyen.model.Book;
import com.mycompany.quanlytruyen.model.Chapter;
import com.mycompany.quanlytruyen.model.BetaStatus;
import com.mycompany.quanlytruyen.model.Post;
import com.mycompany.quanlytruyen.dao.PostDao;

import javax.sql.DataSource;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.AbstractTableModel;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.awt.Frame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.DateTimeException;
import java.time.DayOfWeek;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Arrays;
import java.util.concurrent.ExecutionException;
import java.util.stream.Collectors;

import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;


public class DangTruyen extends javax.swing.JPanel {


    private static final MediaType JSON_MEDIA_TYPE = MediaType.parse("application/json; charset=utf-8");
    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private static final String POST_URL = "https://s1apihd.com/wp-json/v1/app/user/themchuong";
    private static final int DEFAULT_NUM_CHAPTER = 5;

    private DataSource dataSource;
    private BookDao bookDao;
    private AccountDAO accountDao;
    private ChapterDao chapterDao;
    private PostDao postDao;

    private final OkHttpClient httpClient = new OkHttpClient();
    private final ObjectMapper objectMapper = new ObjectMapper();
    private final BookTableModel bookTableModel = new BookTableModel();
    private final Map<Long, Account> accountCache = new HashMap<>();
    private final List<Account> accountList = new ArrayList<>();

    private boolean suppressAccountComboEvents;
    private boolean suppressSelectAllEvents;
    private Long currentAccountFilter;
    private boolean postingInProgress;


    public DangTruyen() {
        initComponents();

        configureTable();
        initializeDateFields();
        initializeDataAccess();
        loadAccountsAsync();
        loadBooksAsync(null);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbooks = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        sideBox = new javax.swing.JPanel();
        FilterPanel2 = new javax.swing.JPanel();
        tenTruyen1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnFilter4 = new javax.swing.JButton();
        btnFilter5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnFilter2 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 40, 85));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btnEdit.setBackground(new java.awt.Color(0, 40, 85));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icon/edit.png"))); // NOI18N
        btnEdit.setBorder(null);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 40, 85));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icon/refresh.png"))); // NOI18N
        btnReset.setBorder(null);
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtSearch.setForeground(new java.awt.Color(153, 153, 153));
        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 40, 85));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icon/search.png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("UVN Chim Bien", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Đăng Truyện Hằng Ngày");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(183, 183, 183)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        Tbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Chọn","Tài khoản", "Tên Truyện", "Giá/chương", "Từ Chương", "Đến Chương"
            }
        ));
        jScrollPane1.setViewportView(Tbooks);

        jCheckBox1.setText("Chọn tất cả");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        FilterPanel2.setBackground(new java.awt.Color(249, 245, 245));
        FilterPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tenTruyen1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tenTruyen1.setPreferredSize(new java.awt.Dimension(100, 22));
        tenTruyen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenTruyen1ActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Tài khoản");

        btnFilter4.setBackground(new java.awt.Color(255, 130, 0));
        btnFilter4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFilter4.setForeground(new java.awt.Color(255, 255, 255));
        btnFilter4.setText("Lọc");
        btnFilter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilter4ActionPerformed(evt);
            }
        });

        btnFilter5.setBackground(new java.awt.Color(153, 153, 153));
        btnFilter5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFilter5.setForeground(new java.awt.Color(255, 255, 255));
        btnFilter5.setText("Xóa Lọc");
        btnFilter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilter5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FilterPanel2Layout = new javax.swing.GroupLayout(FilterPanel2);
        FilterPanel2.setLayout(FilterPanel2Layout);
        FilterPanel2Layout.setHorizontalGroup(
            FilterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(FilterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FilterPanel2Layout.createSequentialGroup()
                        .addComponent(tenTruyen1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(FilterPanel2Layout.createSequentialGroup()
                        .addComponent(btnFilter4)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilter5)))
                .addGap(0, 85, Short.MAX_VALUE))
        );
        FilterPanel2Layout.setVerticalGroup(
            FilterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(FilterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenTruyen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(FilterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFilter4)
                    .addComponent(btnFilter5))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Ngày đăng:");

        day.setText("13");
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });

        month.setText("11");
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        year.setText("2025");
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("/");

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("/");

        javax.swing.GroupLayout sideBoxLayout = new javax.swing.GroupLayout(sideBox);
        sideBox.setLayout(sideBoxLayout);
        sideBoxLayout.setHorizontalGroup(
            sideBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBoxLayout.createSequentialGroup()
                        .addComponent(FilterPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(sideBoxLayout.createSequentialGroup()
                        .addGroup(sideBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(sideBoxLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(sideBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sideBoxLayout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(jLabel13)
                    .addContainerGap(230, Short.MAX_VALUE)))
        );
        sideBoxLayout.setVerticalGroup(
            sideBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBoxLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(FilterPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sideBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(314, Short.MAX_VALUE))
            .addGroup(sideBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sideBoxLayout.createSequentialGroup()
                    .addGap(237, 237, 237)
                    .addComponent(jLabel13)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );

        btnFilter2.setBackground(new java.awt.Color(255, 130, 0));
        btnFilter2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFilter2.setForeground(new java.awt.Color(255, 255, 255));
        btnFilter2.setText("ĐĂNG");
        btnFilter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilter2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(btnFilter2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sideBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFilter2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnResetActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnFilter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilter2ActionPerformed
        // TODO add your handling code here:
        if (postingInProgress) {
            JOptionPane.showMessageDialog(this, "Đang xử lý yêu cầu trước, vui lòng đợi.");
            return;
        }

        if (Tbooks.isEditing()) {
            Tbooks.getCellEditor().stopCellEditing();
        }

        LocalDate scheduleDate = parseSelectedDate();
        if (scheduleDate == null) {
            return;
        }

        List<BookEntry> selectedEntries = bookTableModel.getSelectedEntries();
        if (selectedEntries.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một truyện để đăng.");
            return;
        }

        if (!ensureDataAccessReady()) {
            return;
        }

        postingInProgress = true;
        btnFilter2.setEnabled(false);

        SwingWorker<PostingSummary, Void> worker = new SwingWorker<>() {
            @Override
            protected PostingSummary doInBackground() {
                return postSelectedBooks(selectedEntries, scheduleDate);
            }

            @Override
            protected void done() {
                postingInProgress = false;
                btnFilter2.setEnabled(true);
                try {
                    PostingSummary summary = get();
                    displayPostingSummary(summary);
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                    JOptionPane.showMessageDialog(DangTruyen.this, "Tác vụ đăng đã bị gián đoạn.");
                } catch (ExecutionException ex) {
                    String message = ex.getCause() != null ? ex.getCause().getMessage() : ex.getMessage();
                    JOptionPane.showMessageDialog(DangTruyen.this, "Lỗi khi đăng truyện: " + message);
                }
                loadBooksAsync(currentAccountFilter);
            }
        };
        worker.execute();


    }//GEN-LAST:event_btnFilter2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
                if (suppressSelectAllEvents) {
            return;
        }
        boolean select = jCheckBox1.isSelected();
        bookTableModel.setAllSelected(select);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void tenTruyen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenTruyen1ActionPerformed
        // TODO add your handling code here:
        if (suppressAccountComboEvents) {
            return;
        }
        applyAccountFilter();
  
    }//GEN-LAST:event_tenTruyen1ActionPerformed

    private void btnFilter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilter4ActionPerformed
        // TODO add your handling code here:
        applyAccountFilter();
    }//GEN-LAST:event_btnFilter4ActionPerformed

    private void btnFilter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilter5ActionPerformed
        // TODO add your handling code here:
        suppressAccountComboEvents = true;
        try {
            if (tenTruyen1.getItemCount() > 0) {
                tenTruyen1.setSelectedIndex(0);
            }
        } finally {
            suppressAccountComboEvents = false;
        }
        currentAccountFilter = null;
        loadBooksAsync(null);
    }//GEN-LAST:event_btnFilter5ActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed


    private void configureTable() {
        Tbooks.setModel(bookTableModel);
        Tbooks.setRowHeight(28);
        Tbooks.setAutoCreateRowSorter(true);
        Tbooks.setFillsViewportHeight(true);
        Tbooks.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        TableColumnModel columnModel = Tbooks.getColumnModel();
        if (columnModel != null && columnModel.getColumnCount() >= 6) {
            int[] preferred = {70, 140, 240, 90, 90, 90};
            for (int i = 0; i < preferred.length && i < columnModel.getColumnCount(); i++) {
                TableColumn column = columnModel.getColumn(i);
                column.setPreferredWidth(preferred[i]);
            }
        }
    }

    private void initializeDateFields() {
        LocalDate defaultDate = LocalDate.now().plusDays(1);
        updateDateFields(defaultDate);
    }

    private void updateDateFields(LocalDate date) {
        if (date == null) {
            return;
        }
        day.setText(String.format(Locale.getDefault(), "%02d", date.getDayOfMonth()));
        month.setText(String.format(Locale.getDefault(), "%02d", date.getMonthValue()));
        year.setText(String.valueOf(date.getYear()));
    }

    private void initializeDataAccess() {
        try {
            AppConfig config = AppConfig.getInstance();
            dataSource = DataSourceFactory.create(
                config.getDatabaseUrl(),
                config.getDatabaseUser(),
                config.getDatabasePassword()
            );
            bookDao = new BookDao(dataSource);
            accountDao = new AccountDAO(dataSource);
            chapterDao = new ChapterDao(dataSource);
            postDao = new PostDao(dataSource);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Không thể khởi tạo kết nối CSDL: " + ex.getMessage());
        }
    }

    private void loadAccountsAsync() {
        if (accountDao == null) {
            tenTruyen1.setModel(new DefaultComboBoxModel<>(new String[]{"Tất cả tài khoản"}));
            return;
        }

        new SwingWorker<List<Account>, Void>() {
            private Exception loadException;

            @Override
            protected List<Account> doInBackground() {
                try {
                    return accountDao.getAllAccounts();
                } catch (SQLException ex) {
                    loadException = ex;
                    return Collections.emptyList();
                }
            }

            @Override
            protected void done() {
                try {
                    List<Account> accounts = get();
                    updateAccountCombo(accounts);
                    if (loadException != null) {
                        JOptionPane.showMessageDialog(DangTruyen.this, "Không thể tải danh sách tài khoản: " + loadException.getMessage());
                    }
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                } catch (ExecutionException ex) {
                    String message = ex.getCause() != null ? ex.getCause().getMessage() : ex.getMessage();
                    JOptionPane.showMessageDialog(DangTruyen.this, "Không thể tải danh sách tài khoản: " + message);
                }
            }
        }.execute();
    }

    private void updateAccountCombo(List<Account> accounts) {
        accountList.clear();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Tất cả tài khoản");
        if (accounts != null) {
            for (Account account : accounts) {
                accountList.add(account);
                if (account != null && account.getId() != null) {
                    accountCache.put(account.getId(), account);
                }
                String display = account != null && account.getUsername() != null
                    ? account.getUsername()
                    : "(Không tên)";
                model.addElement(display);
            }
        }
        suppressAccountComboEvents = true;
        try {
            tenTruyen1.setModel(model);
            tenTruyen1.setSelectedIndex(0);
        } finally {
            suppressAccountComboEvents = false;
        }
        bookTableModel.fireTableDataChanged();
    }

    private void loadBooksAsync(Long accountFilter) {
        if (bookDao == null) {
            bookTableModel.setEntries(Collections.emptyList());
            return;
        }

        new SwingWorker<List<BookEntry>, Void>() {
            private Exception loadException;

            @Override
            protected List<BookEntry> doInBackground() {
                try {
                    List<Book> books = bookDao.getAllBooks();
                    List<BookEntry> result = new ArrayList<>();
                    for (Book book : books) {
                        if (book.getPostStatus() != Book.PostStatus.NOT_HOAN) {
                            continue;
                        }
                        if (accountFilter != null) {
                            Long bookAccountId = book.getAccountId();
                            if (bookAccountId == null || !accountFilter.equals(bookAccountId)) {
                                continue;
                            }
                        }
                        Account account = getAccountSafely(book.getAccountId());
                        result.add(new BookEntry(book, account));
                    }
                    return result;
                } catch (SQLException ex) {
                    loadException = ex;
                    return Collections.emptyList();
                }
            }

            @Override
            protected void done() {
                try {
                    List<BookEntry> entries = get();
                    bookTableModel.setEntries(entries);
                    if (loadException != null) {
                        JOptionPane.showMessageDialog(DangTruyen.this, "Không thể tải danh sách truyện: " + loadException.getMessage());
                    }
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                } catch (ExecutionException ex) {
                    String message = ex.getCause() != null ? ex.getCause().getMessage() : ex.getMessage();
                    JOptionPane.showMessageDialog(DangTruyen.this, "Không thể tải danh sách truyện: " + message);
                }
            }
        }.execute();
    }

    private Account getAccountSafely(Long accountId) throws SQLException {
        if (accountId == null) {
            return null;
        }
        Account cached = accountCache.get(accountId);
        if (cached != null) {
            return cached;
        }
        if (accountDao == null) {
            return null;
        }
        Account account = accountDao.getAccountById(accountId);
        if (account != null) {
            accountCache.put(accountId, account);
        }
        return account;
    }

    private void applyAccountFilter() {
        Long accountId = resolveSelectedAccountId();
        currentAccountFilter = accountId;
        loadBooksAsync(accountId);
    }

    private Long resolveSelectedAccountId() {
        int index = tenTruyen1.getSelectedIndex();
        if (index <= 0) {
            return null;
        }
        int accountIndex = index - 1;
        if (accountIndex >= 0 && accountIndex < accountList.size()) {
            Account account = accountList.get(accountIndex);
            return account != null ? account.getId() : null;
        }
        return null;
    }

    private LocalDate parseSelectedDate() {
        String dayText = day.getText() != null ? day.getText().trim() : "";
        String monthText = month.getText() != null ? month.getText().trim() : "";
        String yearText = year.getText() != null ? year.getText().trim() : "";
        if (dayText.isEmpty() || monthText.isEmpty() || yearText.isEmpty()) {
            LocalDate fallback = LocalDate.now().plusDays(1);
            updateDateFields(fallback);
            return fallback;
        }
        try {
            int dayValue = Integer.parseInt(dayText);
            int monthValue = Integer.parseInt(monthText);
            int yearValue = Integer.parseInt(yearText);
            return LocalDate.of(yearValue, monthValue, dayValue);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ngày đăng phải là số hợp lệ.");
        } catch (DateTimeException ex) {
            JOptionPane.showMessageDialog(this, "Ngày đăng không hợp lệ: " + ex.getMessage());
        }
        return null;
    }

    private boolean ensureDataAccessReady() {
        if (bookDao == null || accountDao == null || chapterDao == null || postDao == null) {
            JOptionPane.showMessageDialog(this, "Không thể kết nối cơ sở dữ liệu. Vui lòng kiểm tra cấu hình.");
            return false;
        }
        return true;
    }

    private PostingSummary postSelectedBooks(List<BookEntry> entries, LocalDate scheduleDate) {
        PostingSummary summary = new PostingSummary();
        if (entries == null || scheduleDate == null) {
            return summary;
        }
        for (BookEntry entry : entries) {
            try {
                postBook(entry, scheduleDate, summary);
            } catch (Exception ex) {
                String title = entry != null && entry.getBook() != null && entry.getBook().getTitle() != null
                    ? entry.getBook().getTitle()
                    : "(Không rõ tên truyện)";
                summary.addError(title + ": " + ex.getMessage());
            }
        }
        return summary;
    }

    private void postBook(BookEntry entry, LocalDate scheduleDate, PostingSummary summary) throws Exception {
        if (entry == null) {
            return;
        }
        Book book = entry.getBook();
        if (book == null || book.getId() == null) {
            throw new IllegalStateException("Thiếu thông tin truyện để đăng.");
        }
        Account account = entry.getAccount();
        if (account == null) {
            account = getAccountSafely(book.getAccountId());
            entry.setAccount(account);
        }
        if (account == null) {
            throw new IllegalStateException("Không tìm thấy tài khoản gắn với truyện.");
        }

        List<Post> schedule = postDao.findByBookId(book.getId());
        if (schedule.isEmpty()) {
            throw new IllegalStateException("Chưa có lịch đăng cho truyện này.");
        }

        int fromChapter = entry.getFromChapter();
        int toChapter = entry.getToChapter();
        if (toChapter < fromChapter) {
            throw new IllegalStateException("'Đến chương' phải lớn hơn hoặc bằng 'Từ chương'.");
        }
        int totalChapters = toChapter - fromChapter + 1;
        if (totalChapters <= 0) {
            throw new IllegalStateException("Số lượng chương cần đăng phải lớn hơn 0.");
        }
        if (schedule.size() < totalChapters) {
            throw new IllegalStateException("Lịch đăng hiện có " + schedule.size() + " khung giờ, không đủ cho " + totalChapters + " chương.");
        }

        Map<Integer, Chapter> chapters = loadChaptersForBook(book.getId());
        for (int i = 0; i < totalChapters; i++) {
            int chapterNumber = fromChapter + i;
            Chapter chapter = chapters.get(chapterNumber);
            if (chapter == null) {
                throw new IllegalStateException("Không tìm thấy chương " + chapterNumber + ".");
            }
            if (chapter.getChapterNumber() == null) {
                throw new IllegalStateException("Chương " + chapterNumber + " chưa có số thứ tự hợp lệ.");
            }
            if (chapter.getBetaStatus() != BetaStatus.DONE_BETA && chapter.getBetaStatus() != BetaStatus.DONE_POST) {
                throw new IllegalStateException("Chương " + chapterNumber + " chưa beta xong.");
            }
            if (chapter.getContent() == null || chapter.getContent().isBlank()) {
                throw new IllegalStateException("Chương " + chapterNumber + " chưa có nội dung.");
            }

            Post slot = schedule.get(i);
            LocalDateTime scheduleDateTime = buildScheduleDateTime(scheduleDate, slot);
            List<String> parts = splitChapterContent(chapter.getContent());
            for (int partIndex = 0; partIndex < parts.size(); partIndex++) {
                String content = parts.get(partIndex);
                if (content == null) {
                    content = "";
                }
                String title = buildChapterTitle(chapter, partIndex);
                String auth2 = buildAuth2(book.getId(), chapter.getChapterNumber(), partIndex);
                String requestBody = buildRequestBody(entry, account, title, auth2, scheduleDateTime, content);
                executePostRequest(book, chapter.getChapterNumber(), partIndex, requestBody, summary);
            }
        }
    }

    private Map<Integer, Chapter> loadChaptersForBook(long bookId) throws SQLException {
        Map<Integer, Chapter> result = new HashMap<>();
        List<Chapter> chapters = chapterDao.findByBookId(bookId);
        for (Chapter chapter : chapters) {
            if (chapter.getChapterNumber() != null) {
                result.put(chapter.getChapterNumber(), chapter);
            }
        }
        return result;
    }

    private LocalDateTime buildScheduleDateTime(LocalDate baseDate, Post slot) {
        if (baseDate == null) {
            baseDate = LocalDate.now().plusDays(1);
        }
        if (slot == null) {
            return LocalDateTime.of(baseDate, LocalTime.of(0, 0));
        }
        int hour = slot.getHour();
        int minute = slot.getMinute();
        try {
            if (hour == 24 && minute == 0) {
                return LocalDateTime.of(baseDate.plusDays(1), LocalTime.MIDNIGHT);
            }
            return LocalDateTime.of(baseDate, LocalTime.of(hour, minute));
        } catch (DateTimeException ex) {
            throw new IllegalStateException("Khung giờ không hợp lệ: " + ex.getMessage());
        }
    }

    private List<String> splitChapterContent(String content) {
        String normalized = normalizeChapterContent(content);
        String[] parts = splitContent(normalized, 2);
        List<String> result = new ArrayList<>();
        if (parts != null) {
            result.addAll(Arrays.asList(parts));
        }
        while (result.size() < 2) {
            result.add("");
        }
        return result;
    }

    private String normalizeChapterContent(String content) {
        if (content == null || content.isEmpty()) {
            return "";
        }
        String normalized = content.replace("\r\n", "\n").replace("\r", "\n");
        normalized = normalized.replaceAll("\\n\\s+\\n", "\n\n");
        normalized = normalized.replaceAll("(?<=\\S)\\n(?=\\s*\\S)", "\n\n");
        normalized = normalized.replaceAll("\\n{3,}", "\n\n");

        String[] paragraphs = normalized.split("\\n{2}");
        StringBuilder processed = new StringBuilder();
        for (String paragraph : paragraphs) {
            String cleanedParagraph = removeLeadingSpaces(paragraph);
            if (cleanedParagraph.isEmpty()) {
                continue;
            }
            String capitalized = capitalizeFirstLetter(cleanedParagraph);
            if (processed.length() > 0) {
                processed.append("\n\n");
            }
            processed.append(capitalized);
        }
        return processed.toString();
    }

    private String removeLeadingSpaces(String paragraph) {
        int index = 0;
        while (index < paragraph.length() && paragraph.charAt(index) == ' ') {
            index++;
        }
        return paragraph.substring(index);
    }

    private String capitalizeFirstLetter(String paragraph) {
        for (int i = 0; i < paragraph.length(); i++) {
            char current = paragraph.charAt(i);
            if (Character.isLetter(current)) {
                if (!Character.isUpperCase(current)) {
                    return paragraph.substring(0, i) + Character.toUpperCase(current) + paragraph.substring(i + 1);
                }
                break;
            }
        }
        return paragraph;
    }

    private String[] splitContent(String content, int n) {
        if (n <= 0) {
            return new String[]{content};
        }
        String[] result = new String[n];
        int len = content.length();
        int start = 0;
        for (int i = 0; i < n; i++) {
            if (i == n - 1) {
                result[i] = content.substring(start);
            } else {
                int approxEnd = start + (len - start) / (n - i);
                int idx = content.lastIndexOf('\n', approxEnd);
                if (idx < start) {
                    idx = approxEnd;
                }
                int end = idx;
                if (idx < len && idx >= 0 && content.charAt(idx) == '\n') {
                    end = idx + 1;
                }
                result[i] = content.substring(start, Math.min(end, len));
                start = Math.min(end, len);
                while (start < len && (content.charAt(start) == '\n' || content.charAt(start) == '\r')) {
                    start++;
                }
            }
        }
        return result;
    }

    private String buildChapterTitle(Chapter chapter, int partIndex) {
        int chapterNumber = chapter.getChapterNumber() != null ? chapter.getChapterNumber() : 0;
        String suffix = partIndex == 0 ? ".1" : ".2";
        String baseTitle = chapter.getChapterTitle() != null ? chapter.getChapterTitle() : "";
        return "Chương " + chapterNumber + suffix + ":" + baseTitle;
    }

    private String buildAuth2(long bookId, int chapterNumber, int partIndex) {
        int order = partIndex == 0 ? chapterNumber * 2 - 1 : chapterNumber * 2;
        return "TruyenHD" + bookId + order + "themchuong";
    }

    private String buildRequestBody(BookEntry entry, Account account, String title, String auth2,
                                    LocalDateTime scheduleDateTime, String content) throws IOException {
        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("price", entry.getPriceString());
        payload.put("registered", defaultString(account.getRegistered(), DATE_TIME_FORMATTER.format(LocalDateTime.now())));
        payload.put("title", title);
        payload.put("auth2", auth2);
        payload.put("user_id", account.getId() != null ? account.getId().toString() : "");
        payload.put("activation_key", defaultString(account.getActivationKey(), ""));
        payload.put("versionIOS", defaultString(account.getVersionIos(), "1"));
        payload.put("auth", defaultString(account.getAuth(), ""));
        payload.put("date_schedule", DATE_TIME_FORMATTER.format(scheduleDateTime));
        payload.put("suggest_password", "");
        payload.put("id", entry.getBook().getId().toString());
        payload.put("content", content);
        payload.put("email", defaultString(account.getEmail(), ""));
        payload.put("value_password", "");
        payload.put("uuid", defaultString(account.getUuid(), ""));
        payload.put("status", "future");
        return objectMapper.writeValueAsString(payload);
    }

    private void executePostRequest(Book book, int chapterNumber, int partIndex, String requestBody,
                                    PostingSummary summary) throws IOException {
        RequestBody body = RequestBody.create(requestBody, JSON_MEDIA_TYPE);
        Request request = new Request.Builder()
            .url(POST_URL)
            .post(body)
            .header("Host", "s1apihd.com")
            .header("accept", "*/*")
            .header("content-type", "application/json")
            .header("user-agent", "TruyenHD/2.3 (com.vnvnads.TruyenHD; build:32; iOS 18.3.1) Alamofire/5.9.0")
            .header("accept-language", "vi-VN;q=1.0, en-VN;q=0.9")
            .build();
        try (Response response = httpClient.newCall(request).execute()) {
            if (!response.isSuccessful()) {
                String responseBody = response.body() != null ? response.body().string() : "";
                throw new IOException("HTTP " + response.code() + " - " + responseBody);
            }
        }
        String partSuffix = partIndex == 0 ? ".1" : ".2";
        summary.addSuccess(book.getTitle() + " chương " + chapterNumber + partSuffix);
    }

    private String defaultString(String value, String fallback) {
        return value != null && !value.isBlank() ? value : fallback;
    }

    private void displayPostingSummary(PostingSummary summary) {
        if (summary == null) {
            JOptionPane.showMessageDialog(this, "Không có kết quả để hiển thị.");
            return;
        }
        StringBuilder message = new StringBuilder();
        if (summary.getSuccessCount() > 0) {
            message.append("Thành công: ").append(summary.getSuccessCount()).append(" yêu cầu.\n");
        }
        if (summary.hasErrors()) {
            message.append("Lỗi:\n");
            for (String error : summary.getErrorMessages()) {
                message.append("- ").append(error).append('\n');
            }
            JOptionPane.showMessageDialog(this, message.toString(), "Kết quả đăng", JOptionPane.WARNING_MESSAGE);
        } else {
            String content = message.length() > 0 ? message.toString() : "Không có yêu cầu nào được gửi.";
            JOptionPane.showMessageDialog(this, content, "Kết quả đăng", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private static class PostingSummary {
        private final List<String> successMessages = new ArrayList<>();
        private final List<String> errorMessages = new ArrayList<>();

        void addSuccess(String message) {
            successMessages.add(message);
        }

        void addError(String message) {
            errorMessages.add(message);
        }

        int getSuccessCount() {
            return successMessages.size();
        }

        List<String> getErrorMessages() {
            return errorMessages;
        }

        boolean hasErrors() {
            return !errorMessages.isEmpty();
        }
    }

    private class BookEntry {
        private final Book book;
        private Account account;
        private final BigDecimal price;
        private boolean selected;
        private final int fromChapter;
        private int chapterOffset;

        BookEntry(Book book, Account account) {
            this.book = book;
            this.account = account;
            this.price = book.getPrice() != null ? book.getPrice() : BigDecimal.ZERO;
            int posted = book.getPosted() != null ? book.getPosted() : 0;
            this.fromChapter = posted + 1;
            this.chapterOffset = DEFAULT_NUM_CHAPTER;
        }

        Book getBook() {
            return book;
        }

        Account getAccount() {
            return account;
        }

        void setAccount(Account account) {
            this.account = account;
        }

        boolean isSelected() {
            return selected;
        }

        void setSelected(boolean selected) {
            this.selected = selected;
        }

        int getFromChapter() {
            return fromChapter;
        }

        int getToChapter() {
            return fromChapter + chapterOffset;
        }

        void setToChapter(int toChapter) {
            if (toChapter < fromChapter) {
                throw new IllegalArgumentException("'Đến chương' phải lớn hơn hoặc bằng 'Từ chương'.");
            }
            this.chapterOffset = toChapter - fromChapter;
        }

        String getAccountName() {
            return account != null && account.getUsername() != null ? account.getUsername() : "(Chưa gán)";
        }

        String getBookTitle() {
            return book.getTitle() != null ? book.getTitle() : "";
        }

        String getPriceDisplay() {
            return price != null ? price.stripTrailingZeros().toPlainString() : "0";
        }

        String getPriceString() {
            return getPriceDisplay();
        }
    }

    private class BookTableModel extends AbstractTableModel {
        private final String[] columns = {"Chọn", "Tài khoản", "Tên Truyện", "Giá/chương", "Từ Chương", "Đến Chương"};
        private final List<BookEntry> entries = new ArrayList<>();

        @Override
        public int getRowCount() {
            return entries.size();
        }

        @Override
        public int getColumnCount() {
            return columns.length;
        }

        @Override
        public String getColumnName(int column) {
            return columns[column];
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return switch (columnIndex) {
                case 0 -> Boolean.class;
                case 4, 5 -> Integer.class;
                default -> String.class;
            };
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return columnIndex == 0 || columnIndex == 5;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            BookEntry entry = entries.get(rowIndex);
            return switch (columnIndex) {
                case 0 -> entry.isSelected();
                case 1 -> entry.getAccountName();
                case 2 -> entry.getBookTitle();
                case 3 -> entry.getPriceDisplay();
                case 4 -> entry.getFromChapter();
                case 5 -> entry.getToChapter();
                default -> null;
            };
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            BookEntry entry = entries.get(rowIndex);
            if (columnIndex == 0) {
                entry.setSelected(Boolean.TRUE.equals(aValue));
                fireTableRowsUpdated(rowIndex, rowIndex);
            } else if (columnIndex == 5) {
                Integer parsed = parseInteger(aValue);
                if (parsed == null) {
                    JOptionPane.showMessageDialog(DangTruyen.this, "'Đến chương' phải là số.");
                    return;
                }
                try {
                    entry.setToChapter(parsed);
                    fireTableRowsUpdated(rowIndex, rowIndex);
                } catch (IllegalArgumentException ex) {
                    JOptionPane.showMessageDialog(DangTruyen.this, ex.getMessage());
                }
            }
        }

        private Integer parseInteger(Object value) {
            if (value == null) {
                return null;
            }
            if (value instanceof Number) {
                return ((Number) value).intValue();
            }
            String text = value.toString().trim();
            if (text.isEmpty()) {
                return null;
            }
            try {
                return Integer.parseInt(text);
            } catch (NumberFormatException ex) {
                return null;
            }
        }

        void setEntries(List<BookEntry> newEntries) {
            entries.clear();
            if (newEntries != null) {
                entries.addAll(newEntries);
            }
            suppressSelectAllEvents = true;
            try {
                jCheckBox1.setSelected(false);
            } finally {
                suppressSelectAllEvents = false;
            }
            fireTableDataChanged();
        }

        void setAllSelected(boolean selected) {
            for (BookEntry entry : entries) {
                entry.setSelected(selected);
            }
            if (!entries.isEmpty()) {
                fireTableRowsUpdated(0, entries.size() - 1);
            }
        }

        List<BookEntry> getSelectedEntries() {
            return entries.stream()
                .filter(BookEntry::isSelected)
                .collect(Collectors.toList());
        }
    }
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FilterPanel2;
    private javax.swing.JTable Tbooks;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFilter2;
    private javax.swing.JButton btnFilter4;
    private javax.swing.JButton btnFilter5;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField day;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField month;
    private javax.swing.JPanel sideBox;
    private javax.swing.JComboBox<String> tenTruyen1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
