package com.mycompany.quanlytruyen.view.books;

import com.mycompany.quanlytruyen.config.AppConfig;
import com.mycompany.quanlytruyen.dao.AccountDAO;
import com.mycompany.quanlytruyen.dao.BookDao;
import com.mycompany.quanlytruyen.dao.ChapterDao;
import com.mycompany.quanlytruyen.dao.DataSourceFactory;
import com.mycompany.quanlytruyen.model.Account;
import com.mycompany.quanlytruyen.model.Book;

import javax.sql.DataSource;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.TransferHandler;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ThemSach extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(ThemSach.class.getName());
    private static File lastDirectory;

    private final QLSach parentPanel;
    private final BookDao bookDao;
    private final ChapterDao chapterDao;
    private final AccountDAO accountDao;
    private final List<Account> accountsList = new ArrayList<>();
    private final String guidelinePlaceholder;
    private final String nameTablePlaceholder;
    private File selectedGuidelineFile;
    private File selectedNameTableFile;
    
    public ThemSach(java.awt.Frame parent, boolean modal, QLSach parentPanel) {
        super(parent, modal);
        this.parentPanel = parentPanel;
        DataSource dataSource = createDataSource();
        BookDao panelBookDao = parentPanel != null ? parentPanel.getBookDao() : null;
        this.bookDao = panelBookDao != null ? panelBookDao : (dataSource != null ? new BookDao(dataSource) : null);
        this.chapterDao = dataSource != null ? new ChapterDao(dataSource) : null;
        this.accountDao = dataSource != null ? new AccountDAO(dataSource) : null;
        initComponents();
        setLocationRelativeTo(parent);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        guidelinePlaceholder = txtYeuCau1.getText();
        nameTablePlaceholder = txtBangTen.getText();
        initStatusCombos();
        loadAccounts();
        setupFileInteractions();
        if (bookDao == null) {
            JOptionPane.showMessageDialog(this, "Không thể kết nối cơ sở dữ liệu quản lý truyện");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnProfile = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnProfile1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        yeuCauPanel1 = new javax.swing.JPanel();
        btnYeuCau1 = new javax.swing.JButton();
        txtYeuCau1 = new javax.swing.JTextField();
        bangTenPanel = new javax.swing.JPanel();
        btnBangTen = new javax.swing.JButton();
        txtBangTen = new javax.swing.JTextField();
        stRaw = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        stTranslate = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        stPost = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        txtName3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        accounts = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnProfile.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Thêm Truyện");

        pnProfile1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Tên Truyện:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Tác giả:");

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(0, 153, 0));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Thêm");
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        txtName.setToolTipText("");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });

        yeuCauPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnYeuCau1.setBackground(new java.awt.Color(0, 153, 153));
        btnYeuCau1.setForeground(new java.awt.Color(255, 255, 255));
        btnYeuCau1.setText("Yêu Cầu");
        btnYeuCau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeuCau1ActionPerformed(evt);
            }
        });

        txtYeuCau1.setEditable(false);
        txtYeuCau1.setForeground(new java.awt.Color(153, 153, 153));
        txtYeuCau1.setText("File Yêu Cầu .txt");
        txtYeuCau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYeuCau1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout yeuCauPanel1Layout = new javax.swing.GroupLayout(yeuCauPanel1);
        yeuCauPanel1.setLayout(yeuCauPanel1Layout);
        yeuCauPanel1Layout.setHorizontalGroup(
            yeuCauPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeuCauPanel1Layout.createSequentialGroup()
                .addComponent(txtYeuCau1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnYeuCau1)
                .addGap(83, 83, 83))
        );
        yeuCauPanel1Layout.setVerticalGroup(
            yeuCauPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeuCauPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(yeuCauPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYeuCau1)
                    .addComponent(txtYeuCau1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bangTenPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnBangTen.setBackground(new java.awt.Color(0, 102, 102));
        btnBangTen.setForeground(new java.awt.Color(255, 255, 255));
        btnBangTen.setText("Bảng Tên");
        btnBangTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangTenActionPerformed(evt);
            }
        });

        txtBangTen.setEditable(false);
        txtBangTen.setForeground(new java.awt.Color(153, 153, 153));
        txtBangTen.setText("File Bảng Tên .csv");
        txtBangTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBangTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bangTenPanelLayout = new javax.swing.GroupLayout(bangTenPanel);
        bangTenPanel.setLayout(bangTenPanelLayout);
        bangTenPanelLayout.setHorizontalGroup(
            bangTenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bangTenPanelLayout.createSequentialGroup()
                .addComponent(txtBangTen)
                .addGap(10, 10, 10)
                .addComponent(btnBangTen)
                .addGap(78, 78, 78))
        );
        bangTenPanelLayout.setVerticalGroup(
            bangTenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bangTenPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(bangTenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBangTen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBangTen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stRaw.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stRaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stRawActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Tình trạng Raw");

        stTranslate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stTranslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stTranslateActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Tình trạng Dịch");

        stPost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stPostActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Tình trạng Đăng");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Tên Ngắn:");

        txtName1.setToolTipText("");
        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });

        txtName3.setText("0");
        txtName3.setToolTipText("");
        txtName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName3ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Số chương đã đăng");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Giá mỗi chương");

        txtName2.setText("250");
        txtName2.setToolTipText("");
        txtName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Tài khoản:");

        accounts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnProfile1Layout = new javax.swing.GroupLayout(pnProfile1);
        pnProfile1.setLayout(pnProfile1Layout);
        pnProfile1Layout.setHorizontalGroup(
            pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfile1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnProfile1Layout.createSequentialGroup()
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(126, 126, 126)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnProfile1Layout.createSequentialGroup()
                            .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel23)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19))
                            .addGap(18, 18, 18)
                            .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(accounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnProfile1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bangTenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yeuCauPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfile1Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfile1Layout.createSequentialGroup()
                        .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnProfile1Layout.createSequentialGroup()
                        .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfile1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfile1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(stRaw, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnProfile1Layout.createSequentialGroup()
                            .addComponent(stPost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5))
                        .addGroup(pnProfile1Layout.createSequentialGroup()
                            .addComponent(stTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4))))
                .addGap(81, 81, 81))
        );
        pnProfile1Layout.setVerticalGroup(
            pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfile1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(25, 25, 25)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(yeuCauPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(bangTenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stRaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout pnProfileLayout = new javax.swing.GroupLayout(pnProfile);
        pnProfile.setLayout(pnProfileLayout);
        pnProfileLayout.setHorizontalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfileLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(291, 291, 291))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfileLayout.createSequentialGroup()
                        .addComponent(pnProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnProfileLayout.setVerticalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnProfile, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        dispose();
    }//GEN-LAST:event_closeDialog

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if (bookDao == null) {
            JOptionPane.showMessageDialog(this, "Không thể kết nối cơ sở dữ liệu để thêm truyện");
            return;
        }

        String title = textOf(txtName);
        if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên truyện");
            txtName.requestFocus();
            return;
        }

        String shortTitle = emptyToNull(textOf(txtName2));
        String author = emptyToNull(textOf(txtAuthor));
        BigDecimal price;
        try {
            price = parsePrice(textOf(txtName3));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Giá mỗi chương phải là số hợp lệ");
            txtName3.requestFocus();
            return;
        }

        Integer postedChapters;
        try {
            postedChapters = parsePostedChapters(textOf(txtName1));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Số chương đã đăng phải là số nguyên không âm");
            txtName1.requestFocus();
            return;
        }

        Book.RawStatus rawStatus = getSelectedRawStatus();
        Book.TranslateStatus translateStatus = getSelectedTranslateStatus();
        Book.PostStatus postStatus = getSelectedPostStatus();

        Account selectedAccount = getSelectedAccount();
        String guidelinesPath = resolveFilePath(txtYeuCau1.getText(), guidelinePlaceholder);
        String nameTablePath = resolveFilePath(txtBangTen.getText(), nameTablePlaceholder);

        Book book = new Book();
        book.setTitle(title);
        book.setShortTitle(shortTitle);
        book.setAuthor(author);
        book.setRawStatus(rawStatus);
        book.setTranslateStatus(translateStatus);
        book.setPostStatus(postStatus);
        book.setGuidelines(guidelinesPath);
        book.setNameTable(nameTablePath);
        book.setPrice(price);
        book.setPosted(postedChapters);
        book.setAccountId(selectedAccount != null ? selectedAccount.getId() : null);

        try {
            bookDao.createBook(book);
            updateChapterPostedStatus(book.getId(), postedChapters);
            JOptionPane.showMessageDialog(this, "Thêm truyện thành công");
            if (parentPanel != null) {
                parentPanel.refreshBooks();
            }
            dispose();
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "Không thể thêm truyện", ex);
            JOptionPane.showMessageDialog(this, "Không thể thêm truyện: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        // TODO add your handling code here:
        btnCreateActionPerformed(null);
    }//GEN-LAST:event_btnCreateMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnYeuCau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeuCau1ActionPerformed
        // TODO add your handling code here:
        chooseGuidelineFile();
    }//GEN-LAST:event_btnYeuCau1ActionPerformed

    private void txtYeuCau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYeuCau1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYeuCau1ActionPerformed

    private void btnBangTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangTenActionPerformed
        // TODO add your handling code here:
    chooseNameTableFile();
    }//GEN-LAST:event_btnBangTenActionPerformed

    private void txtBangTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBangTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBangTenActionPerformed
 

    
    private void stRawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stRawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stRawActionPerformed

    private void stTranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stTranslateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stTranslateActionPerformed

    private void stPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stPostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stPostActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void txtName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName3ActionPerformed

    private void txtName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName2ActionPerformed

    private DataSource createDataSource() {
        try {
            AppConfig config = AppConfig.getInstance();
            return DataSourceFactory.create(
                config.getDatabaseUrl(),
                config.getDatabaseUser(),
                config.getDatabasePassword()
            );
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Không thể khởi tạo kết nối cơ sở dữ liệu", ex);
            return null;
        }
    }

    private void initStatusCombos() {
        DefaultComboBoxModel<String> rawModel = new DefaultComboBoxModel<>();
        for (Book.RawStatus status : Book.RawStatus.values()) {
            rawModel.addElement(status.getDisplayName());
        }
        stRaw.setModel(rawModel);
        if (rawModel.getSize() > 0) {
            stRaw.setSelectedIndex(0);
        }

        DefaultComboBoxModel<String> translateModel = new DefaultComboBoxModel<>();
        for (Book.TranslateStatus status : Book.TranslateStatus.values()) {
            translateModel.addElement(status.getDisplayName());
        }
        stTranslate.setModel(translateModel);
        if (translateModel.getSize() > 0) {
            stTranslate.setSelectedIndex(0);
        }

        DefaultComboBoxModel<String> postModel = new DefaultComboBoxModel<>();
        for (Book.PostStatus status : Book.PostStatus.values()) {
            postModel.addElement(status.getDisplayName());
        }
        stPost.setModel(postModel);
        if (postModel.getSize() > 0) {
            stPost.setSelectedIndex(0);
        }
    }

    private void loadAccounts() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        accountsList.clear();
        model.addElement("-- Chọn tài khoản --");

        if (accountDao != null) {
            try {
                accountsList.addAll(accountDao.getAllAccounts());
                for (Account account : accountsList) {
                    model.addElement(account.getUsername());
                }
            } catch (SQLException ex) {
                logger.log(Level.SEVERE, "Không thể tải danh sách tài khoản", ex);
                JOptionPane.showMessageDialog(this, "Không thể tải danh sách tài khoản: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không thể kết nối để tải danh sách tài khoản");
        }

        accounts.setModel(model);
        accounts.setSelectedIndex(model.getSize() > 0 ? 0 : -1);
    }

    private Account getSelectedAccount() {
        int index = accounts.getSelectedIndex();
        if (index <= 0) {
            return null;
        }
        int listIndex = index - 1;
        if (listIndex >= 0 && listIndex < accountsList.size()) {
            return accountsList.get(listIndex);
        }
        return null;
    }

    private void setupFileInteractions() {
        configureFileDrop(txtYeuCau1, "file yêu cầu (.txt)", "txt");
        configureFileDrop(txtBangTen, "file bảng tên (.csv)", "csv");
    }

    private void configureFileDrop(JTextField targetField, String description, String... extensions) {
        targetField.setTransferHandler(new TransferHandler() {
            @Override
            public boolean canImport(TransferSupport support) {
                if (!support.isDataFlavorSupported(DataFlavor.javaFileListFlavor)) {
                    return false;
                }
                support.setDropAction(TransferHandler.COPY);
                return true;
            }

            @Override
            public boolean importData(TransferSupport support) {
                if (!canImport(support)) {
                    return false;
                }
                try {
                    List<?> data = (List<?>) support.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    if (data == null || data.isEmpty()) {
                        return false;
                    }
                    Object first = data.get(0);
                    if (!(first instanceof File)) {
                        return false;
                    }
                    File file = (File) first;
                    if (!isSupportedExtension(file, extensions)) {
                        JOptionPane.showMessageDialog(ThemSach.this,
                            "Định dạng không hợp lệ, " + description);
                        return false;
                    }
                    applyFileSelection(targetField, file);
                    return true;
                } catch (UnsupportedFlavorException | IOException ex) {
                    logger.log(Level.WARNING, "Không thể nhận file được kéo thả", ex);
                    return false;
                }
            }
        });
    }

    private void applyFileSelection(JTextField targetField, File file) {
        if (targetField == txtYeuCau1) {
            setGuidelineFile(file);
        } else if (targetField == txtBangTen) {
            setNameTableFile(file);
        }
    }

    private void chooseGuidelineFile() {
        chooseFile("Chọn file yêu cầu", txtYeuCau1, "txt");
    }

    private void chooseNameTableFile() {
        chooseFile("Chọn file bảng tên", txtBangTen, "csv");
    }

    private void chooseFile(String dialogTitle, JTextField targetField, String... extensions) {
        JFileChooser chooser = lastDirectory != null ? new JFileChooser(lastDirectory) : new JFileChooser();
        chooser.setDialogTitle(dialogTitle);
        chooser.setFileFilter(new FileNameExtensionFilter(dialogTitle, extensions));
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            if (!isSupportedExtension(file, extensions)) {
                JOptionPane.showMessageDialog(this, "File không đúng định dạng yêu cầu");
                return;
            }
            lastDirectory = file.getParentFile();
            applyFileSelection(targetField, file);
        }
    }

    private boolean isSupportedExtension(File file, String... extensions) {
        if (file == null || extensions == null) {
            return false;
        }
        String name = file.getName().toLowerCase();
        for (String extension : extensions) {
            if (extension == null) {
                continue;
            }
            String normalized = extension.toLowerCase();
            if (!normalized.startsWith(".")) {
                normalized = "." + normalized;
            }
            if (name.endsWith(normalized)) {
                return true;
            }
        }
        return false;
    }

    private void setGuidelineFile(File file) {
        selectedGuidelineFile = file;
        if (file != null) {
            txtYeuCau1.setText(file.getAbsolutePath());
        }
    }

    private void setNameTableFile(File file) {
        selectedNameTableFile = file;
        if (file != null) {
            txtBangTen.setText(file.getAbsolutePath());
        }
    }

    private String resolveFilePath(String text, String placeholder) {
        if (text == null) {
            return null;
        }
        String trimmed = text.trim();
        if (trimmed.isEmpty()) {
            return null;
        }
        if (placeholder != null && Objects.equals(trimmed, placeholder.trim())) {
            return null;
        }
        return trimmed;
    }

    private String textOf(JTextField field) {
        return field.getText() == null ? "" : field.getText().trim();
    }

    private String emptyToNull(String value) {
        return value == null || value.isBlank() ? null : value;
    }

    private BigDecimal parsePrice(String text) {
        if (text == null || text.isBlank()) {
            return BigDecimal.ZERO;
        }
        String normalized = text.replaceAll("[,\\s]", "").trim();
        if (normalized.isEmpty()) {
            return BigDecimal.ZERO;
        }
        return new BigDecimal(normalized);
    }

    private Integer parsePostedChapters(String text) {
        if (text == null || text.isBlank()) {
            return 0;
        }
        String normalized = text.trim();
        int value = Integer.parseInt(normalized);
        if (value < 0) {
            throw new NumberFormatException("negative");
        }
        return value;
    }

    private Book.RawStatus getSelectedRawStatus() {
        Object selected = stRaw.getSelectedItem();
        String display = selected != null ? selected.toString() : null;
        for (Book.RawStatus status : Book.RawStatus.values()) {
            if (Objects.equals(status.getDisplayName(), display)) {
                return status;
            }
        }
        return Book.RawStatus.NOT_FULL;
    }

    private Book.TranslateStatus getSelectedTranslateStatus() {
        Object selected = stTranslate.getSelectedItem();
        String display = selected != null ? selected.toString() : null;
        for (Book.TranslateStatus status : Book.TranslateStatus.values()) {
            if (Objects.equals(status.getDisplayName(), display)) {
                return status;
            }
        }
        return Book.TranslateStatus.NOT_HOAN;
    }

    private Book.PostStatus getSelectedPostStatus() {
        Object selected = stPost.getSelectedItem();
        String display = selected != null ? selected.toString() : null;
        for (Book.PostStatus status : Book.PostStatus.values()) {
            if (Objects.equals(status.getDisplayName(), display)) {
                return status;
            }
        }
        return Book.PostStatus.NOT_HOAN;
    }

    private void updateChapterPostedStatus(long bookId, Integer postedChapters) {
        if (chapterDao == null || postedChapters == null || postedChapters <= 0) {
            return;
        }
        try {
            chapterDao.markChaptersAsPostedUpTo(bookId, postedChapters);
        } catch (SQLException ex) {
            logger.log(Level.WARNING, "Không thể cập nhật trạng thái đăng của các chương", ex);
        }
    }    
    /**
     * @param args the command line arguments
     */

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accounts;
    private javax.swing.JPanel bangTenPanel;
    private javax.swing.JButton btnBangTen;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnYeuCau1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnProfile;
    private javax.swing.JPanel pnProfile1;
    private javax.swing.JComboBox<String> stPost;
    private javax.swing.JComboBox<String> stRaw;
    private javax.swing.JComboBox<String> stTranslate;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBangTen;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtName3;
    private javax.swing.JTextField txtYeuCau1;
    private javax.swing.JPanel yeuCauPanel1;
    // End of variables declaration//GEN-END:variables

}
