package com.mycompany.quanlytruyen.view.books;

import com.mycompany.quanlytruyen.config.AppConfig;
import com.mycompany.quanlytruyen.dao.AccountDAO;
import com.mycompany.quanlytruyen.dao.BookDao;
import com.mycompany.quanlytruyen.dao.ChapterDao;
import com.mycompany.quanlytruyen.dao.DataSourceFactory;
import com.mycompany.quanlytruyen.model.Account;
import com.mycompany.quanlytruyen.model.Book;
import com.mycompany.quanlytruyen.service.FileService;
import com.mycompany.quanlytruyen.utils.UIUtils;
import com.mycompany.quanlytruyen.utils.TextFieldKeyboardUtils;

import javax.sql.DataSource;
import javax.swing.*;
import java.awt.Color;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetAdapter;
import java.awt.dnd.DropTargetDropEvent;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Function;


public class ThemSach extends javax.swing.JDialog {

    private final QLSach parentPanel;
    private final FileService fileService = new FileService();
    private final AppConfig config = AppConfig.getInstance();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ThemSach.class.getName());

    private String guidelines;
    private String nameTable;

    private final Book.RawStatus[] rawStatuses = Book.RawStatus.values();
    private final Book.TranslateStatus[] translateStatuses = Book.TranslateStatus.values();
    private final Book.PostStatus[] postStatuses = Book.PostStatus.values();
    private final DataSource dataSource;
    private final BookDao bookDao;
    private final AccountDAO accountDao;
    private final ChapterDao chapterDao;

    private DefaultComboBoxModel<AccountItem> accountModel;

    public ThemSach(java.awt.Frame parent, boolean modal, QLSach parentPanel) {
        super(parent, modal);
        this.parentPanel = parentPanel;
        initComponents();
        jLabel18.setText("Giá mỗi chương:");
        jLabel6.setText("Tên ngắn:");
        setupKeyboardShortcuts();
        UIUtils.enableTextComponentShortcuts(this);

        DataSource tmpDataSource = null;
        BookDao tmpBookDao = null;
        AccountDAO tmpAccountDao = null;
        ChapterDao tmpChapterDao = null;
        try {
            tmpDataSource = createDataSource();
            tmpBookDao = new BookDao(tmpDataSource);
            tmpAccountDao = new AccountDAO(tmpDataSource);
            tmpChapterDao = new ChapterDao(tmpDataSource);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Không thể khởi tạo kết nối: " + ex.getMessage());
        }
        this.dataSource = tmpDataSource;
        this.bookDao = tmpBookDao;
        this.accountDao = tmpAccountDao;
        this.chapterDao = tmpChapterDao;

        populateStatusCombos();
        loadAccounts();
        setupDragAndDrop();
       // setHandler();
    }
    private void setupKeyboardShortcuts() {
        // Setup keyboard shortcuts cho tất cả text fields trong form
        TextFieldKeyboardUtils.setupEnhancedTextComponent(txtName);
        TextFieldKeyboardUtils.setupEnhancedTextComponent(txtAuthor);
        TextFieldKeyboardUtils.setupEnhancedTextComponent(txtYeuCau1);
        TextFieldKeyboardUtils.setupEnhancedTextComponent(txtBangTen);
    } 
    /*
    private void  setHandler(){
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRefresh1ActionPerformed(evt);
        }
        });
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnProfile = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnProfile1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        yeuCauPanel1 = new javax.swing.JPanel();
        btnYeuCau1 = new javax.swing.JButton();
        txtYeuCau1 = new javax.swing.JTextField();
        bangTenPanel = new javax.swing.JPanel();
        btnBangTen = new javax.swing.JButton();
        txtBangTen = new javax.swing.JTextField();
        stRaw = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        stTranslate = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        stPost = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        txtName3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        accounts = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnProfile.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Thêm Truyện");

        pnProfile1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Tên Truyện:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Tác giả:");

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(0, 153, 0));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Thêm");
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        txtName.setToolTipText("");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });

        yeuCauPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnYeuCau1.setBackground(new java.awt.Color(0, 153, 153));
        btnYeuCau1.setForeground(new java.awt.Color(255, 255, 255));
        btnYeuCau1.setText("Yêu Cầu");
        btnYeuCau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeuCau1ActionPerformed(evt);
            }
        });

        txtYeuCau1.setEditable(false);
        txtYeuCau1.setForeground(new java.awt.Color(153, 153, 153));
        txtYeuCau1.setText("File Yêu Cầu .txt");
        txtYeuCau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYeuCau1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout yeuCauPanel1Layout = new javax.swing.GroupLayout(yeuCauPanel1);
        yeuCauPanel1.setLayout(yeuCauPanel1Layout);
        yeuCauPanel1Layout.setHorizontalGroup(
            yeuCauPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeuCauPanel1Layout.createSequentialGroup()
                .addComponent(txtYeuCau1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnYeuCau1)
                .addGap(83, 83, 83))
        );
        yeuCauPanel1Layout.setVerticalGroup(
            yeuCauPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeuCauPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(yeuCauPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYeuCau1)
                    .addComponent(txtYeuCau1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bangTenPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnBangTen.setBackground(new java.awt.Color(0, 102, 102));
        btnBangTen.setForeground(new java.awt.Color(255, 255, 255));
        btnBangTen.setText("Bảng Tên");
        btnBangTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangTenActionPerformed(evt);
            }
        });

        txtBangTen.setEditable(false);
        txtBangTen.setForeground(new java.awt.Color(153, 153, 153));
        txtBangTen.setText("File Bảng Tên .csv");
        txtBangTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBangTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bangTenPanelLayout = new javax.swing.GroupLayout(bangTenPanel);
        bangTenPanel.setLayout(bangTenPanelLayout);
        bangTenPanelLayout.setHorizontalGroup(
            bangTenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bangTenPanelLayout.createSequentialGroup()
                .addComponent(txtBangTen)
                .addGap(10, 10, 10)
                .addComponent(btnBangTen)
                .addGap(78, 78, 78))
        );
        bangTenPanelLayout.setVerticalGroup(
            bangTenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bangTenPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(bangTenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBangTen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBangTen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stRaw.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stRaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stRawActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Tình trạng Raw");

        stTranslate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stTranslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stTranslateActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Tình trạng Dịch");

        stPost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stPostActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Tình trạng Đăng");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Tên Ngắn:");

        txtName1.setToolTipText("");
        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });

        txtName3.setText("0");
        txtName3.setToolTipText("");
        txtName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName3ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Số chương đã đăng");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Giá mỗi chương");

        txtName2.setText("250");
        txtName2.setToolTipText("");
        txtName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Tài khoản:");

        accounts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnProfile1Layout = new javax.swing.GroupLayout(pnProfile1);
        pnProfile1.setLayout(pnProfile1Layout);
        pnProfile1Layout.setHorizontalGroup(
            pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfile1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnProfile1Layout.createSequentialGroup()
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(126, 126, 126)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnProfile1Layout.createSequentialGroup()
                            .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel23)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19))
                            .addGap(18, 18, 18)
                            .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(accounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnProfile1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bangTenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yeuCauPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfile1Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfile1Layout.createSequentialGroup()
                        .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnProfile1Layout.createSequentialGroup()
                        .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfile1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfile1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(stRaw, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnProfile1Layout.createSequentialGroup()
                            .addComponent(stPost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5))
                        .addGroup(pnProfile1Layout.createSequentialGroup()
                            .addComponent(stTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4))))
                .addGap(81, 81, 81))
        );
        pnProfile1Layout.setVerticalGroup(
            pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfile1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(25, 25, 25)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(yeuCauPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(bangTenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stRaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout pnProfileLayout = new javax.swing.GroupLayout(pnProfile);
        pnProfile.setLayout(pnProfileLayout);
        pnProfileLayout.setHorizontalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfileLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(291, 291, 291))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfileLayout.createSequentialGroup()
                        .addComponent(pnProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnProfileLayout.setVerticalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnProfile, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        dispose();
    }//GEN-LAST:event_closeDialog

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String title = txtName.getText().trim();
        if (title.isEmpty()) {
            showWarning("Vui lòng nhập Tên Truyện");
            return;
        }

        Book book = new Book();
        book.setTitle(title);
        book.setAuthor(txtAuthor.getText().trim());
        book.setGuidelines(guidelines);
        book.setNameTable(nameTable);
        book.setRawStatus((Book.RawStatus) stRaw.getSelectedItem());
        book.setTranslateStatus((Book.TranslateStatus) stTranslate.getSelectedItem());
        book.setPostStatus((Book.PostStatus) stPost.getSelectedItem());
        book.setShortTitle(txtName1.getText().trim());

        AccountItem selectedAccount = (AccountItem) accounts.getSelectedItem();
        book.setAccountId(selectedAccount != null ? selectedAccount.id() : null);

        BigDecimal price = parsePrice();
        if (price == null) {
            return;
        }
        book.setPrice(price);

        Integer postedChapters = parsePostedChapters();
        if (postedChapters == null) {
            return;
        }
        book.setPosted(postedChapters);

        try {
            if (bookDao == null) {
                showError("Không thể kết nối cơ sở dữ liệu");
                return;
            }
            bookDao.createBook(book);
            if (chapterDao != null && postedChapters > 0) {
                chapterDao.markChaptersAsPostedFrom(book.getId(), postedChapters);
            }
            showInfo("Thêm truyện thành công");
            dispose();
        } catch (Exception e) {
            showError("Không thể thêm truyện: " + e.getMessage());
        }        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        // TODO add your handling code here:
        btnCreateActionPerformed(null);
    }//GEN-LAST:event_btnCreateMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnYeuCau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeuCau1ActionPerformed
        // TODO add your handling code here:
        File file = fileService.selectTextFile(this, "Chọn file yêu cầu");
        if (file != null) {
            handleGuidelinesFile(file);
        }
    }//GEN-LAST:event_btnYeuCau1ActionPerformed

    private void txtYeuCau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYeuCau1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYeuCau1ActionPerformed

    private void btnBangTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangTenActionPerformed
        // TODO add your handling code here:
        File file = fileService.selectTextFile(this, "Chọn file bảng tên");
        if (file != null) {
            handleNameTableFile(file);
        }
    }//GEN-LAST:event_btnBangTenActionPerformed

    private void txtBangTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBangTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBangTenActionPerformed
 
    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        guidelines = null;
        txtYeuCau1.setText("(File Yêu Cầu)");
        txtYeuCau1.setForeground(new java.awt.Color(153,153,153));
    }//
    
    private void stRawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stRawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stRawActionPerformed

    private void stTranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stTranslateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stTranslateActionPerformed

    private void stPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stPostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stPostActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void txtName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName3ActionPerformed

    private void txtName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName2ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void populateStatusCombos() {
        configureStatusCombo(stRaw, rawStatuses, Book.RawStatus::getDisplayName);
        configureStatusCombo(stTranslate, translateStatuses, Book.TranslateStatus::getDisplayName);
        configureStatusCombo(stPost, postStatuses, Book.PostStatus::getDisplayName);
    }

    private <T> void configureStatusCombo(JComboBox<T> comboBox, T[] values, Function<T, String> displayFn) {
        DefaultComboBoxModel<T> model = new DefaultComboBoxModel<>(values);
        comboBox.setModel(model);
        comboBox.setRenderer(new DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value != null) {
                    @SuppressWarnings("unchecked")
                    T typedValue = (T) value;
                    setText(displayFn.apply(typedValue));
                } else {
                    setText("");
                }
                return this;
            }
        });
    }
    private void loadAccounts() {
        accountModel = new DefaultComboBoxModel<>();
        accountModel.addElement(AccountItem.empty());
        accounts.setModel(accountModel);
        accounts.setRenderer(new DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof AccountItem item) {
                    setText(item.getDisplayName());
                }
                return this;
            }
        });

        if (accountDao == null) {
            return;
        }
        try {
            List<Account> accountsData = accountDao.getAllAccounts();
            for (Account account : accountsData) {
                accountModel.addElement(AccountItem.of(account));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Không thể tải tài khoản: " + e.getMessage());
        }
    }    

    private void setupDragAndDrop() {
        setupFileDropTarget(txtYeuCau1, this::handleGuidelinesFile);
        setupFileDropTarget(txtBangTen, this::handleNameTableFile);
    }

    private void setupFileDropTarget(JTextField textField, Consumer<File> handler) {
        new DropTarget(textField, new DropTargetAdapter() {
            @Override
            public void drop(DropTargetDropEvent dtde) {
                try {
                    dtde.acceptDrop(DnDConstants.ACTION_COPY);
                    Transferable t = dtde.getTransferable();
                    if (t.isDataFlavorSupported(DataFlavor.javaFileListFlavor)) {
                        @SuppressWarnings("unchecked")
                        List<File> files = (List<File>) t.getTransferData(DataFlavor.javaFileListFlavor);
                        if (!files.isEmpty()) {
                            handler.accept(files.get(0));
                        }
                    }
                    dtde.dropComplete(true);
                } catch (Exception ex) {
                    showError("Không thể xử lý file: " + ex.getMessage());
                    dtde.dropComplete(false);
                }
            }
        });
    }

    private void handleGuidelinesFile(File file) {
        try {
            guidelines = fileService.readTextFile(file);
            txtYeuCau1.setText(file.getName());
            txtYeuCau1.setForeground(Color.BLACK);
        } catch (IOException e) {
            showError("Không thể đọc file yêu cầu: " + e.getMessage());
        }
    }

    private void handleNameTableFile(File file) {
        try {
            nameTable = fileService.readTextFile(file);
            txtBangTen.setText(file.getName());
            txtBangTen.setForeground(Color.BLACK);
        } catch (IOException e) {
            showError("Không thể đọc file bảng tên: " + e.getMessage());
        }
    }
    private BigDecimal parsePrice() {
        String text = txtName2.getText().trim();
        if (text.isEmpty()) {
            return BigDecimal.ZERO;
        }
        try {
            return new BigDecimal(text);
        } catch (NumberFormatException ex) {
            showError("Giá chương không hợp lệ");
            return null;
        }
    }

    private Integer parsePostedChapters() {
        String text = txtName3.getText().trim();
        if (text.isEmpty()) {
            return 0;
        }
        try {
            int value = Integer.parseInt(text);
            if (value < 0) {
                showError("Số chương đã đăng phải lớn hơn hoặc bằng 0");
                return null;
            }
            return value;
        } catch (NumberFormatException ex) {
            showError("Số chương đã đăng không hợp lệ");
            return null;
        }
    }    

    private DataSource createDataSource() {
        return DataSourceFactory.create(
                config.getDatabaseUrl(),
                config.getDatabaseUser(),
                config.getDatabasePassword());
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    private void showWarning(String message) {
        JOptionPane.showMessageDialog(this, message, "Cảnh báo", JOptionPane.WARNING_MESSAGE);
    }

    private void showInfo(String message) {
        JOptionPane.showMessageDialog(this, message, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accounts;
    private javax.swing.JPanel bangTenPanel;
    private javax.swing.JButton btnBangTen;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnYeuCau1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnProfile;
    private javax.swing.JPanel pnProfile1;
    private javax.swing.JComboBox<String> stPost;
    private javax.swing.JComboBox<String> stRaw;
    private javax.swing.JComboBox<String> stTranslate;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBangTen;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtName3;
    private javax.swing.JTextField txtYeuCau1;
    private javax.swing.JPanel yeuCauPanel1;
    // End of variables declaration//GEN-END:variables

    private record AccountItem(Long id, String name) {
        static AccountItem empty() {
            return new AccountItem(null, "-- Chưa chọn --");
        }

        static AccountItem of(Account account) {
            return new AccountItem(account.getId(), account.getUsername());
        }

        String getDisplayName() {
            return name;
        }
    }    
}
