/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlytruyen.view.chiachuong;

import com.mycompany.quanlytruyen.view.HomeFrame;
import com.mycompany.quanlytruyen.view.books.QLSach;
import static com.mysql.cj.conf.PropertyKey.logger;

import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author trang
 */
public class ChiaChuong1 extends javax.swing.JPanel {

    /**
     * Creates new form ChiaChuong1
     */
    public ChiaChuong1() {
        initComponents();
  
        btncopy2.addActionListener(evt -> copyToClipboard(part2.getText()));
        btncopy3.addActionListener(evt -> copyToClipboard(part3.getText()));
        btncopy4.addActionListener(evt -> copyToClipboard(part4.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        pnProfile1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        part = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        part1 = new javax.swing.JTextArea();
        btncopy1 = new javax.swing.JButton();
        part2 = new javax.swing.JTextArea();
        btncopy2 = new javax.swing.JButton();
        part3 = new javax.swing.JTextArea();
        btncopy3 = new javax.swing.JButton();
        btncopy4 = new javax.swing.JButton();
        part4 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chapterContent = new javax.swing.JTextArea();

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Chia Chương");

        pnProfile1.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Đóng");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(0, 153, 0));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Chia");
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Chia thành mấy phần:");

        part.setText("2");
        part.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partActionPerformed(evt);
            }
        });

        part1.setColumns(20);
        part1.setRows(5);
        part1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btncopy1.setBackground(new java.awt.Color(204, 204, 204));
        btncopy1.setText("copy");
        btncopy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncopy1ActionPerformed(evt);
            }
        });

        part2.setColumns(20);
        part2.setRows(5);
        part2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btncopy2.setBackground(new java.awt.Color(204, 204, 204));
        btncopy2.setText("copy");
        btncopy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncopy2ActionPerformed(evt);
            }
        });

        part3.setColumns(20);
        part3.setRows(5);
        part3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btncopy3.setBackground(new java.awt.Color(204, 204, 204));
        btncopy3.setText("copy");
        btncopy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncopy3ActionPerformed(evt);
            }
        });

        btncopy4.setBackground(new java.awt.Color(204, 204, 204));
        btncopy4.setText("copy");
        btncopy4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncopy4ActionPerformed(evt);
            }
        });

        part4.setColumns(20);
        part4.setRows(5);
        part4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btncopy4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(part4, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncopy3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(part3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncopy2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(part2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btncopy1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(part1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(26, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(part2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncopy2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(part3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncopy3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(part4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncopy4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(part1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btncopy1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Nội Dung");

        chapterContent.setColumns(20);
        chapterContent.setRows(5);
        jScrollPane1.setViewportView(chapterContent);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnProfile1Layout = new javax.swing.GroupLayout(pnProfile1);
        pnProfile1.setLayout(pnProfile1Layout);
        pnProfile1Layout.setHorizontalGroup(
            pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfile1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(part, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfile1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfile1Layout.createSequentialGroup()
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfile1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfile1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnProfile1Layout.setVerticalGroup(
            pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfile1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(pnProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateMouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String content = chapterContent.getText();
        content = normalizeParagraphs(content);
        chapterContent.setText(content);
        int n;
        try {
            n = Integer.parseInt(part.getText().trim());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Số phần không hợp lệ");
            return;
        }
        if (n <= 0 || n > 4) {
            javax.swing.JOptionPane.showMessageDialog(this, "Số phần phải từ 1 đến 4");
            return;
        }
        String[] parts = splitContent(content, n);
        javax.swing.JTextArea[] areas = {part1, part2, part3, part4};
        for (int i = 0; i < areas.length; i++) {
            if (i < parts.length) {
                areas[i].setText(parts[i]);
            } else {
                areas[i].setText("");
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void partActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partActionPerformed

    private void btncopy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncopy1ActionPerformed
        // TODO add your handling code here:
        copyToClipboard(part1.getText());
    }//GEN-LAST:event_btncopy1ActionPerformed

    private void btncopy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncopy2ActionPerformed
        // TODO add your handling code here:
        copyToClipboard(part2.getText());
    }//GEN-LAST:event_btncopy2ActionPerformed

    private void btncopy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncopy3ActionPerformed
        // TODO add your handling code here:
        copyToClipboard(part3.getText());
    }//GEN-LAST:event_btncopy3ActionPerformed

    private void btncopy4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncopy4ActionPerformed
        // TODO add your handling code here:
        copyToClipboard(part4.getText());
    }//GEN-LAST:event_btncopy4ActionPerformed

        private String normalizeParagraphs(String content) {
        if (content == null || content.isEmpty()) {
            return content;
        }

        String normalized = content.replace("\r\n", "\n").replace("\r", "\n");
        normalized = normalized.replaceAll("\\n\\s+\\n", "\n\n");
        normalized = normalized.replaceAll("(?<=\\S)\\n(?=\\s*\\S)", "\n\n");
        normalized = normalized.replaceAll("\\n{3,}", "\n\n");

        String[] paragraphs = normalized.split("\\n{2}");
        StringBuilder processed = new StringBuilder();
        for (String paragraph : paragraphs) {
            String cleanedParagraph = removeLeadingSpaces(paragraph);
            if (cleanedParagraph.isEmpty()) {
                continue;
            }
            String capitalizedParagraph = capitalizeFirstLetter(cleanedParagraph);
            if (processed.length() > 0) {
                processed.append("\n\n");
            }
            processed.append(capitalizedParagraph);
        }
        return processed.toString();
    }

    private String removeLeadingSpaces(String paragraph) {
        int index = 0;
        while (index < paragraph.length() && paragraph.charAt(index) == ' ') {
            index++;
        }
        return paragraph.substring(index);
    }

    private String capitalizeFirstLetter(String paragraph) {
        for (int i = 0; i < paragraph.length(); i++) {
            char current = paragraph.charAt(i);
            if (Character.isLetter(current)) {
                if (!Character.isUpperCase(current)) {
                    return paragraph.substring(0, i) + Character.toUpperCase(current) + paragraph.substring(i + 1);
                }
                break;
            }
        }
        return paragraph;
    }

    private String[] splitContent(String content, int n) {
        String[] result = new String[n];
        int len = content.length();
        int start = 0;
        for (int i = 0; i < n; i++) {
            if (i == n - 1) {
                result[i] = content.substring(start);
            } else {
                int approxEnd = start + (len - start) / (n - i);
                int idx = content.lastIndexOf('\n', approxEnd);
                if (idx < start) {
                    idx = approxEnd;
                }
                int end = idx;
                if (idx < len && content.charAt(idx) == '\n') {
                    end = idx + 1;
                }
                result[i] = content.substring(start, end);
                start = end;
                while (start < len && (content.charAt(start) == '\n' || content.charAt(start) == '\r')) {
                    start++;
                }
            }
        }
        return result;
    }

    private void copyToClipboard(String text) {
        StringSelection selection = new StringSelection(text);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(selection, selection);
        //javax.swing.JOptionPane.showMessageDialog(this, "Đã copy vào clipboard");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btncopy1;
    private javax.swing.JButton btncopy2;
    private javax.swing.JButton btncopy3;
    private javax.swing.JButton btncopy4;
    private javax.swing.JTextArea chapterContent;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField part;
    private javax.swing.JTextArea part1;
    private javax.swing.JTextArea part2;
    private javax.swing.JTextArea part3;
    private javax.swing.JTextArea part4;
    private javax.swing.JPanel pnProfile1;
    // End of variables declaration//GEN-END:variables
}
