package com.mycompany.quanlytruyen.view;

import com.mycompany.quanlytruyen.view.books.QLSach;
import com.mycompany.quanlytruyen.view.books.ThemSach;
import com.mycompany.quanlytruyen.view.chapters.ChiaChuong;
import com.mycompany.quanlytruyen.view.chapters.QLChuong;
import com.mycompany.quanlytruyen.view.chiachuong.ChiaChuong1;
import com.mycompany.quanlytruyen.view.translate.QLDich;
import com.mycompany.quanlytruyen.view.accounts.QLTK;
import com.mycompany.quanlytruyen.view.post.DangTruyen;

import javax.swing.*;
import java.awt.*;

public class HomeFrame extends javax.swing.JFrame {
    
    private JPanel contentPanel;

    public HomeFrame() {
        initComponents();
        initNavigation();

    }

    private void initNavigation() {
            // Create content panel for dynamic content
            contentPanel = new JPanel(new BorderLayout());

            // Clear jPanel1 and set it up properly
            jPanel1.removeAll();
            jPanel1.setLayout(new BorderLayout());
            jPanel1.add(contentPanel, BorderLayout.CENTER);

            // Set up button actions
            btnBooks1.addActionListener(e -> showPanel(new QLSach()));
            btnchapters2.addActionListener(e -> showPanel(new QLChuong()));
            btnTranslate.addActionListener(e -> showPanel(new QLDich()));
            btnAccounts.addActionListener(e -> showPanel(new QLTK()));
            btnPost.addActionListener(e -> showPanel(new DangTruyen()));
            
            btnChiaChuong.addActionListener(e -> showPanel(new ChiaChuong1()));

            // Show default panel
            showPanel(new QLSach());
        }


    private void showPanel(JPanel panel) {
        contentPanel.removeAll();
        contentPanel.add(panel, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }    
      
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnchapters2 = new javax.swing.JButton();
        btnBooks1 = new javax.swing.JButton();
        btnTranslate = new javax.swing.JButton();
        btnPost = new javax.swing.JButton();
        btnChiaChuong = new javax.swing.JButton();
        btnAccounts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1136, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 40, 85));
        jPanel9.setForeground(new java.awt.Color(214, 177, 240));

        btnchapters2.setBackground(new java.awt.Color(255, 130, 0));
        btnchapters2.setFont(new java.awt.Font("Yuanti SC", 1, 18)); // NOI18N
        btnchapters2.setForeground(new java.awt.Color(255, 255, 255));
        btnchapters2.setText("Quản Lý Từng Chương");
        btnchapters2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchapters2ActionPerformed(evt);
            }
        });

        btnBooks1.setBackground(new java.awt.Color(255, 130, 0));
        btnBooks1.setFont(new java.awt.Font("Yuanti SC", 1, 18)); // NOI18N
        btnBooks1.setForeground(new java.awt.Color(255, 255, 255));
        btnBooks1.setText("Quản Lý Truyện");
        btnBooks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBooks1ActionPerformed(evt);
            }
        });

        btnTranslate.setBackground(new java.awt.Color(0, 153, 51));
        btnTranslate.setFont(new java.awt.Font("Yuanti SC", 1, 16)); // NOI18N
        btnTranslate.setForeground(new java.awt.Color(255, 255, 255));
        btnTranslate.setText("DỊCH API");
        btnTranslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranslateActionPerformed(evt);
            }
        });

        btnPost.setBackground(new java.awt.Color(102, 102, 102));
        btnPost.setFont(new java.awt.Font("Yuanti SC", 1, 14)); // NOI18N
        btnPost.setForeground(new java.awt.Color(255, 255, 255));
        btnPost.setText("Đăng Truyện Hàng Ngày");
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });

        btnChiaChuong.setBackground(new java.awt.Color(255, 102, 51));
        btnChiaChuong.setFont(new java.awt.Font("Yuanti SC", 1, 14)); // NOI18N
        btnChiaChuong.setForeground(new java.awt.Color(255, 255, 255));
        btnChiaChuong.setText("Chia Chương");
        btnChiaChuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaChuongActionPerformed(evt);
            }
        });

        btnAccounts.setBackground(new java.awt.Color(255, 130, 0));
        btnAccounts.setFont(new java.awt.Font("Yuanti SC", 1, 18)); // NOI18N
        btnAccounts.setForeground(new java.awt.Color(255, 255, 255));
        btnAccounts.setText("Quản Lý Tài Khoản");
        btnAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnchapters2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBooks1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
            .addComponent(btnAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btnTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btnPost)
                        .addGap(42, 42, 42))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnChiaChuong)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBooks1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnchapters2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(btnTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChiaChuong)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPostActionPerformed

    private void btnchapters2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchapters2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchapters2ActionPerformed

    private void btnBooks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBooks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBooks1ActionPerformed

    private void btnChiaChuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaChuongActionPerformed
        // TODO add your handling code here:    
            //fireEditingStopped();
            //String content = (String) tableModel.getValueAt(row, 5);
    }//GEN-LAST:event_btnChiaChuongActionPerformed

    private void btnTranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranslateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTranslateActionPerformed

    private void btnAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccountsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeFrame().setVisible(true));
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccounts;
    private javax.swing.JButton btnBooks1;
    private javax.swing.JButton btnChiaChuong;
    private javax.swing.JButton btnPost;
    private javax.swing.JButton btnTranslate;
    private javax.swing.JButton btnchapters2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
